[package]
name = "go_analyzer"
version = "0.1.0"
authors = ["aujxn <ajn6@pdx.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sgf-parser = "2.4"
itertools = "0.9"
serde_json = "1.0"
